"""Legacy compatibility for ``gabi.domain.market.scoring``."""

import gabi.domain.market.scoring as _implementation

_percentile = _implementation._percentile
_percentile_within_sector = _implementation._percentile_within_sector
add_percentile_columns = _implementation.add_percentile_columns
compute_block_score = _implementation.compute_block_score
_weighted_row_mean = _implementation._weighted_row_mean
build_scores = _implementation.build_scores
compute_confidence = _implementation.compute_confidence
explain_row = _implementation.explain_row
VALUE_METRICS_LOWER_BETTER = _implementation.VALUE_METRICS_LOWER_BETTER
QUALITY_METRICS_HIGHER_BETTER = _implementation.QUALITY_METRICS_HIGHER_BETTER
MOMENTUM_METRICS_HIGHER_BETTER = _implementation.MOMENTUM_METRICS_HIGHER_BETTER
RISK_METRICS_LOWER_BETTER = _implementation.RISK_METRICS_LOWER_BETTER
RISK_METRICS_HIGHER_BETTER = _implementation.RISK_METRICS_HIGHER_BETTER
DEFAULT_WEIGHTS = _implementation.DEFAULT_WEIGHTS
DEFAULT_MIN_SECTOR_GROUP = _implementation.DEFAULT_MIN_SECTOR_GROUP
MIN_SCORE_COVERAGE = _implementation.MIN_SCORE_COVERAGE
SCORE_METRICS = _implementation.SCORE_METRICS
