"""Piloto de extracción de fundamentales del texto de los 10-K anteriores a XBRL (issue #41).

Antes de construir nada a gran escala hay que medir la precisión. El piloto
extrae ocho partidas del 10-K del ejercicio 2008 (presentado en 2009, sin XBRL)
y las compara con el valor del mismo ejercicio en la primera presentación XBRL
que lo incluye como comparativo. Una discrepancia puede ser un error de
extracción o una reexpresión posterior; ambas cosas cuentan en contra de usar
estos datos.

Documentos: el principal del 10-K y, si existe, el anexo EX-13 (el informe
anual, donde muchas empresas publicaban los estados financieros).

Reglas puras; se ejecuta con ``python -m gabi_cli research tenk-extraction``.
"""

import re
from datetime import date

import numpy as np
import pandas as pd

SAMPLE_SIZE = 30
TOLERANCE = 0.005  # 0,5 % relativo

# (tabla, patrón de etiqueta, duración o instante) por partida; los tags XBRL los aporta el adaptador.
PATTERNS = {
    "revenue": ("income", r"^(total )?(net )?(sales|revenues?|(railway |total )?operating revenues?|sales to customers|"
                          r"net sales and revenues?|revenues?, net)"
                          r"( and other( operating)? (income|revenues?))?$", "duration"),
    "net_income": ("income", r"^net (income|earnings)( \(loss\))?( attributable to [a-z .,&']+)?$", "duration"),
    "operating_income": ("income", r"^(total )?(operating income|income from operations|operating profit|"
                                   r"operating earnings)( \(loss\))?$", "duration"),
    "equity": ("balance", r"^total (common )?(stockholders|shareholders|share ?owners)'?s?'? (equity|investment)$", "instant"),
    "long_term_debt": ("balance", r"^long[- ]term debt( and capital lease obligations)?( ?[,(-]? ?(net|less|excluding) "
                                  r"[a-z ,]+\)?)?$", "instant"),
    "operating_cash_flow": ("cash", r"^(net )?cash( flows?)? (provided by|from|generated by|provided from)"
                                    r"( \(used (in|for)\))? operating activities$", "duration"),
    "capex": ("cash", r"^(capital expenditures|property additions|(additions to|purchases of|payments for|"
                      r"expenditures for|acquisitions? of|investments? in) (property|premises|plant|fixed assets))", "duration"),
    "depreciation": ("cash", r"^depreciation(,| and| &)( depletion(,)? and)? amortization", "duration"),
}
# Una tabla es de un tipo si contiene alguna de sus claves (los balances y
# flujos a veces vienen partidos en dos tablas).
TABLE_KEYS = {"income": ("per share", "net income", "net earnings"), "balance": ("total assets", "total liabilities"),
              "cash": ("operating activities", "investing activities")}
SCALE_PATTERNS = ((1e3, r"in thousands|\(thousands|000s omitted|thousands of (u\.s\. )?dollars|\$000"),
                  (1e6, r"in millions|\(millions|millions of (u\.s\. )?dollars|dollars in millions|\$ millions"),
                  (1e9, r"in billions|\(billions"))
NUMBER = re.compile(r"\(?-?\$?\s*[\d,]+(?:\.\d+)?\)?")


# Tags XBRL adicionales solo para validar el piloto (GABI guarda un subconjunto).
EXTRA_TAGS = {"revenue": ["SalesRevenueGoodsNet", "SalesRevenueServicesNet", "RevenuesNetOfInterestExpense"],
              "net_income": ["ProfitLoss", "NetIncomeLossAvailableToCommonStockholdersBasic"],
              "operating_income": ["OperatingIncomeLoss"],
              "equity": ["StockholdersEquity", "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"],
              "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebtAndCapitalLeaseObligations"],
              "operating_cash_flow": ["NetCashProvidedByUsedInOperatingActivities",
                                      "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations"],
              "capex": ["PaymentsToAcquirePropertyPlantAndEquipment", "PaymentsToAcquireProductiveAssets"],
              "depreciation": ["DepreciationDepletionAndAmortization", "DepreciationAmortizationAndAccretionNet",
                               "DepreciationAndAmortization"]}
WINDOWS_1252 = str.maketrans({"": "'", "’": "'", "": '"', "": '"', "": "-", "": "-", "—": "-", "–": "-"})


def _text(value) -> str:
    return re.sub(r"\s+", " ", str(value).translate(WINDOWS_1252)).strip() if isinstance(value, str) else ""


def _label(text: str) -> str:
    """Etiqueta normalizada: sin referencias a notas ni dos puntos finales."""
    text = re.sub(r"\((see )?notes? [^)]*\)", "", text.lower())
    return re.sub(r"\s+", " ", text).strip(" :")


def _number(token: str) -> float | None:
    cleaned = token.replace("$", "").replace(",", "").replace(" ", "")
    negative = cleaned.startswith("(") or cleaned.startswith("-")
    cleaned = cleaned.strip("()-")
    if not cleaned or not re.fullmatch(r"\d+(\.\d+)?", cleaned):
        return None
    value = float(cleaned)
    return -value if negative else value


def _rows(table: pd.DataFrame) -> list[tuple[str, list[float], list[str]]]:
    """(etiqueta, números en orden, textos de la fila) sin celdas duplicadas por colspan."""
    rows = []
    for _, row in table.iterrows():
        cells = [c for c in dict.fromkeys(_text(v) for v in row.values) if c and c.lower() != "nan"]
        if not cells:
            continue
        label = cells[0] if not NUMBER.fullmatch(cells[0]) else ""
        numbers = [n for c in cells[1 if label else 0:] for n in [_number(c)] if n is not None]
        rows.append((_label(label), numbers, cells))
    return rows


def _scale_in(text: str) -> float | None:
    hits = [(match.start(), factor) for factor, pattern in SCALE_PATTERNS for match in re.finditer(pattern, text)]
    return max(hits)[1] if hits else None  # la mención más cercana al final (la más próxima a la tabla)


def document_text(html: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html)).translate(WINDOWS_1252).lower()


def _scale(table: pd.DataFrame, document: str) -> float:
    """Escala de la tabla: en la propia tabla, en el texto que la precede o la dominante del documento."""
    own = _scale_in(" ".join(_text(v) for v in table.values.ravel()).lower())
    if own:
        return own
    labels = [_text(v).lower() for v in table.values.ravel() if len(_text(v)) >= 20]
    for anchor in labels[:3]:
        position = document.find(anchor)
        if position > 0:
            before = _scale_in(document[max(0, position - 2500):position])
            if before:
                return before
    counts = {factor: len(re.findall(pattern, document)) for factor, pattern in SCALE_PATTERNS}
    best = max(counts, key=lambda f: counts[f])
    return best if counts[best] else 1.0


def _year_order(rows) -> bool:
    """True si la primera columna es el ejercicio más reciente (lo habitual)."""
    for _label, numbers, cells in rows[:8]:
        years = [int(n) for n in numbers if 1990 <= n <= 2012 and float(n).is_integer()]
        if len(years) >= 2:
            return years[0] >= years[-1]
    return True


def extract(documents: list[tuple[list[pd.DataFrame], str]]) -> dict:
    """Las ocho partidas del ejercicio más reciente, en unidades (USD).

    ``documents``: por documento legible, sus tablas y su texto normalizado (``document_text``).
    """
    found: dict[str, float] = {}
    for tables, document in documents:
        for table in tables:
            text = " ".join(_text(v) for v in table.values.ravel()).lower()
            kinds = [kind for kind, keys in TABLE_KEYS.items() if any(k in text for k in keys)]
            if not kinds:
                continue
            rows = _rows(table)
            newest_first = _year_order(rows)
            scale = _scale(table, document)
            for item, (kind, pattern, _period) in PATTERNS.items():
                if item in found or kind not in kinds:
                    continue
                for label, numbers, _cells in rows:
                    values = [n for n in numbers if not (1990 <= abs(n) <= 2012 and float(n).is_integer()
                                                          and len(numbers) > 3)] or numbers
                    if label and re.search(pattern, label) and values:
                        value = values[0] if newest_first else values[-1]
                        found[item] = abs(value) * scale if item == "capex" else value * scale
                        break
    return found


def first_xbrl_value(companyfacts: dict, tags: list[str], period: str,
                     fiscal_end: str) -> tuple[float | None, str | None]:
    """Valor XBRL del ejercicio ``fiscal_end`` en la presentación más temprana que lo incluye (Company Facts)."""
    facts = companyfacts.get("facts", {}).get("us-gaap", {})
    target = date.fromisoformat(fiscal_end)
    for tag in tags:
        rows = []
        for entry in facts.get(tag, {}).get("units", {}).get("USD", []):
            if entry.get("form") not in ("10-K", "10-K/A"):
                continue
            end = date.fromisoformat(entry["end"])
            if abs((end - target).days) > 20:
                continue
            if period == "duration" and not ("start" in entry and
                                             340 <= (end - date.fromisoformat(entry["start"])).days <= 380):
                continue
            rows.append((entry["filed"], float(entry["val"])))
        if rows:
            filed, value = min(rows)
            return value, filed
    return None, None


def split(chosen: list[dict]) -> dict[str, list[dict]]:
    """Fijado antes de mirar ningún fallo: posiciones pares para ajustar, impares reservadas para medir."""
    return {"ajuste": chosen[0::2], "reserva": chosen[1::2]}


def summary(frame: pd.DataFrame, companies: int) -> dict:
    comparable = frame[frame.xbrl.notna()]
    return {"empresas": companies, "tolerancia": TOLERANCE,
            "por_partida": {item: {"con_xbrl": int(len(g)), "extraidas": int(g.extraido.notna().sum()),
                                   "coinciden": int(g.coincide.sum()),
                                   "precision_sobre_extraidas": float(g.coincide.sum() / max(1, g.extraido.notna().sum())),
                                   "cobertura": float(g.extraido.notna().mean()) if len(g) else None}
                            for item, g in comparable.groupby("item")},
            "global": {"comparables": int(len(comparable)), "extraidas": int(comparable.extraido.notna().sum()),
                       "coinciden": int(comparable.coincide.sum()),
                       "error_mediano": float(np.nanmedian(comparable.error_relativo)) if comparable.error_relativo.notna().any() else None}}
