"""Piloto de extracción de fundamentales del texto de los 10-K anteriores a XBRL (issue #41).

Antes de construir nada a gran escala hay que medir la precisión. El piloto
extrae ocho partidas del 10-K del ejercicio 2008 (presentado en 2009, sin XBRL)
y las compara con el valor del mismo ejercicio en la primera presentación XBRL
que lo incluye como comparativo. Una discrepancia puede ser un error de
extracción o una reexpresión posterior; ambas cosas cuentan en contra de usar
estos datos.

Documentos: el principal del 10-K y, si existe, el anexo EX-13 (el informe
anual, donde muchas empresas publicaban los estados financieros).
"""

import argparse
import io
import json
import re
from datetime import date

import numpy as np
import pandas as pd
import requests

from . import config, edgar, identity, sec_history, storage
from . import factor_stability as fs
from . import historical_issuer_evidence as ie

OUTPUT = config.BASE_DIR / "docs" / "tenk-extraction-pilot"
WORK = sec_history.DIRECTORY / "tenk_pilot"
SAMPLE_SIZE = 30
TOLERANCE = 0.005  # 0,5 % relativo

ITEMS = {
    "revenue": ("income", r"^(total )?(net )?(sales|revenues?|(railway |total )?operating revenues?|sales to customers|"
                          r"net sales and revenues?|revenues?, net)"
                          r"( and other( operating)? (income|revenues?))?$", edgar.REVENUE_TAGS, "duration"),
    "net_income": ("income", r"^net (income|earnings)( \(loss\))?( attributable to [a-z .,&']+)?$",
                   edgar.NET_INCOME_TAGS, "duration"),
    "operating_income": ("income", r"^(total )?(operating income|income from operations|operating profit|"
                                   r"operating earnings)( \(loss\))?$", edgar.OPERATING_INCOME_TAGS, "duration"),
    "equity": ("balance", r"^total (common )?(stockholders|shareholders|share ?owners)'?s?'? (equity|investment)$",
               edgar.EQUITY_TAGS, "instant"),
    "long_term_debt": ("balance", r"^long[- ]term debt( and capital lease obligations)?( ?[,(-]? ?(net|less|excluding) "
                                  r"[a-z ,]+\)?)?$", edgar.LT_DEBT_TAGS, "instant"),
    "operating_cash_flow": ("cash", r"^(net )?cash( flows?)? (provided by|from|generated by|provided from)"
                                    r"( \(used (in|for)\))? operating activities$",
                            edgar.OCF_TAGS, "duration"),
    "capex": ("cash", r"^(capital expenditures|property additions|(additions to|purchases of|payments for|"
                      r"expenditures for|acquisitions? of|investments? in) (property|premises|plant|fixed assets))",
              edgar.CAPEX_TAGS, "duration"),
    "depreciation": ("cash", r"^depreciation(,| and| &)( depletion(,)? and)? amortization", edgar.DEPRECIATION_TAGS,
                     "duration"),
}
# Una tabla es de un tipo si contiene alguna de sus claves (los balances y
# flujos a veces vienen partidos en dos tablas).
TABLE_KEYS = {"income": ("per share", "net income", "net earnings"), "balance": ("total assets", "total liabilities"),
              "cash": ("operating activities", "investing activities")}
SCALE_PATTERNS = ((1e3, r"in thousands|\(thousands|000s omitted|thousands of (u\.s\. )?dollars|\$000"),
                  (1e6, r"in millions|\(millions|millions of (u\.s\. )?dollars|dollars in millions|\$ millions"),
                  (1e9, r"in billions|\(billions"))
NUMBER = re.compile(r"\(?-?\$?\s*[\d,]+(?:\.\d+)?\)?")


# Tags XBRL adicionales solo para validar el piloto (GABI guarda un subconjunto).
EXTRA_TAGS = {"revenue": ["SalesRevenueGoodsNet", "SalesRevenueServicesNet", "RevenuesNetOfInterestExpense"],
              "net_income": ["ProfitLoss", "NetIncomeLossAvailableToCommonStockholdersBasic"],
              "operating_income": ["OperatingIncomeLoss"],
              "equity": ["StockholdersEquity", "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"],
              "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebtAndCapitalLeaseObligations"],
              "operating_cash_flow": ["NetCashProvidedByUsedInOperatingActivities",
                                      "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations"],
              "capex": ["PaymentsToAcquirePropertyPlantAndEquipment", "PaymentsToAcquireProductiveAssets"],
              "depreciation": ["DepreciationDepletionAndAmortization", "DepreciationAmortizationAndAccretionNet",
                               "DepreciationAndAmortization"]}
WINDOWS_1252 = str.maketrans({"": "'", "’": "'", "": '"', "": '"', "": "-", "": "-", "—": "-", "–": "-"})


def _text(value) -> str:
    return re.sub(r"\s+", " ", str(value).translate(WINDOWS_1252)).strip() if isinstance(value, str) else ""


def _label(text: str) -> str:
    """Etiqueta normalizada: sin referencias a notas ni dos puntos finales."""
    text = re.sub(r"\((see )?notes? [^)]*\)", "", text.lower())
    return re.sub(r"\s+", " ", text).strip(" :")


def _number(token: str) -> float | None:
    cleaned = token.replace("$", "").replace(",", "").replace(" ", "")
    negative = cleaned.startswith("(") or cleaned.startswith("-")
    cleaned = cleaned.strip("()-")
    if not cleaned or not re.fullmatch(r"\d+(\.\d+)?", cleaned):
        return None
    value = float(cleaned)
    return -value if negative else value


def _rows(table: pd.DataFrame) -> list[tuple[str, list[float], list[str]]]:
    """(etiqueta, números en orden, textos de la fila) sin celdas duplicadas por colspan."""
    rows = []
    for _, row in table.iterrows():
        cells = [c for c in dict.fromkeys(_text(v) for v in row.values) if c and c.lower() != "nan"]
        if not cells:
            continue
        label = cells[0] if not NUMBER.fullmatch(cells[0]) else ""
        numbers = [n for c in cells[1 if label else 0:] for n in [_number(c)] if n is not None]
        rows.append((_label(label), numbers, cells))
    return rows


def _scale_in(text: str) -> float | None:
    hits = [(match.start(), factor) for factor, pattern in SCALE_PATTERNS for match in re.finditer(pattern, text)]
    return max(hits)[1] if hits else None  # la mención más cercana al final (la más próxima a la tabla)


def _document_text(html: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html)).translate(WINDOWS_1252).lower()


def _scale(table: pd.DataFrame, document: str) -> float:
    """Escala de la tabla: en la propia tabla, en el texto que la precede o la dominante del documento."""
    own = _scale_in(" ".join(_text(v) for v in table.values.ravel()).lower())
    if own:
        return own
    labels = [_text(v).lower() for v in table.values.ravel() if len(_text(v)) >= 20]
    for anchor in labels[:3]:
        position = document.find(anchor)
        if position > 0:
            before = _scale_in(document[max(0, position - 2500):position])
            if before:
                return before
    counts = {factor: len(re.findall(pattern, document)) for factor, pattern in SCALE_PATTERNS}
    best = max(counts, key=lambda f: counts[f])
    return best if counts[best] else 1.0


def _year_order(rows) -> bool:
    """True si la primera columna es el ejercicio más reciente (lo habitual)."""
    for _label, numbers, cells in rows[:8]:
        years = [int(n) for n in numbers if 1990 <= n <= 2012 and float(n).is_integer()]
        if len(years) >= 2:
            return years[0] >= years[-1]
    return True


def extract(documents: list[str]) -> dict:
    """Las ocho partidas del ejercicio más reciente, en unidades (USD)."""
    found: dict[str, float] = {}
    for html in documents:
        try:
            tables = pd.read_html(io.StringIO(html))
        except ValueError:
            continue
        document = _document_text(html)
        for table in tables:
            text = " ".join(_text(v) for v in table.values.ravel()).lower()
            kinds = [kind for kind, keys in TABLE_KEYS.items() if any(k in text for k in keys)]
            if not kinds:
                continue
            rows = _rows(table)
            newest_first = _year_order(rows)
            scale = _scale(table, document)
            for item, (kind, pattern, _tags, _period) in ITEMS.items():
                if item in found or kind not in kinds:
                    continue
                for label, numbers, _cells in rows:
                    values = [n for n in numbers if not (1990 <= abs(n) <= 2012 and float(n).is_integer()
                                                          and len(numbers) > 3)] or numbers
                    if label and re.search(pattern, label) and values:
                        value = values[0] if newest_first else values[-1]
                        found[item] = abs(value) * scale if item == "capex" else value * scale
                        break
    return found


def _companyfacts(cik: str) -> dict:
    url = edgar.COMPANYFACTS_URL.format(cik=cik)
    try:
        path = sec_history.download(url, sec_history.DIRECTORY / "companyfacts" / f"CIK{cik}.json")
    except requests.HTTPError as exc:
        # Emisores que nunca presentaron XBRL (desaparecidos antes de 2009): sin comparativos.
        if exc.response is not None and exc.response.status_code == 404:
            return {}
        raise
    return json.loads(path.read_text())


def _xbrl_value(cik: str, tags: list[str], period: str, fiscal_end: str) -> tuple[float | None, str | None]:
    """Valor XBRL del ejercicio ``fiscal_end`` en la presentación más temprana que lo incluye (Company Facts)."""
    facts = _companyfacts(cik).get("facts", {}).get("us-gaap", {})
    target = date.fromisoformat(fiscal_end)
    for tag in tags:
        rows = []
        for entry in facts.get(tag, {}).get("units", {}).get("USD", []):
            if entry.get("form") not in ("10-K", "10-K/A"):
                continue
            end = date.fromisoformat(entry["end"])
            if abs((end - target).days) > 20:
                continue
            if period == "duration" and not ("start" in entry and
                                             340 <= (end - date.fromisoformat(entry["start"])).days <= 380):
                continue
            rows.append((entry["filed"], float(entry["val"])))
        if rows:
            filed, value = min(rows)
            return value, filed
    return None, None


def sample() -> list[dict]:
    """30 miembros del S&P 500 a 2008-12-31 con 10-K del ejercicio 2008 presentado en 2009 y XBRL posterior."""
    from . import historical_membership as hm
    from . import historical_period as hp
    from .historical_identity_audit import CANDIDATE_SOURCE, _candidate_map
    members = hm.constituents_as_of("2008-12-31", source_id=hp.REFERENCE_SOURCE_FULL, compare_reference=False)["symbols"]
    with storage.get_connection() as conn:
        cands = conn.execute("SELECT symbol,cik,name,date_added,date_removed,observed_from FROM "
                             "historical_issuer_candidates WHERE source_id=?", (CANDIDATE_SOURCE,)).fetchall()
    cmap = _candidate_map(cands, "2008-12-31")
    pool = []
    for symbol in sorted(members):
        cik = cmap.get(symbol, {}).get("cik")
        life = ie.listing_life(cik) if cik else None
        reports = [r for r in (life or {}).get("annual_reports", []) if "2009-01-15" <= r["filed"] <= "2009-04-15"]
        if cik and reports:
            revenue, _ = _xbrl_value(identity.normalize_cik(cik), [*edgar.REVENUE_TAGS, *EXTRA_TAGS["revenue"]],
                                     "duration", "2008-12-31")
            if revenue is not None:
                pool.append({"symbol": symbol, "cik": identity.normalize_cik(cik), "report": reports[0]})
    step = max(1, len(pool) // SAMPLE_SIZE)
    return pool[::step][:SAMPLE_SIZE]


def _documents(cik: str, report: dict) -> list[str]:
    accession = report["accession"]
    base = f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{accession.replace('-', '')}"
    index = json.loads(sec_history.download(f"{base}/index.json", WORK / f"{accession}-index.json").read_text())
    names = [report["primary"]] + [item["name"] for item in index["directory"]["item"]
                                   if re.search(r"ex-?13|exv13|ex13", item["name"].lower())
                                   and item["name"].lower().endswith((".htm", ".html"))]
    return [sec_history.download(f"{base}/{name}", WORK / f"{accession}_{name}").read_text(encoding="latin-1")
            for name in dict.fromkeys(names)]


def split(chosen: list[dict]) -> dict[str, list[dict]]:
    """Fijado antes de mirar ningún fallo: posiciones pares para ajustar, impares reservadas para medir."""
    return {"ajuste": chosen[0::2], "reserva": chosen[1::2]}


def run(subset: str | None = None) -> dict:
    rows = []
    chosen = sample() if subset is None else split(sample())[subset]
    for company in chosen:
        extracted = extract(_documents(company["cik"], company["report"]))
        for item, (_kind, _pattern, tags, period) in ITEMS.items():
            xbrl, filed = _xbrl_value(company["cik"], [*tags, *EXTRA_TAGS[item]], period, "2008-12-31")
            value = extracted.get(item)
            error = abs(value - xbrl) / abs(xbrl) if value is not None and xbrl not in (None, 0) else None
            rows.append({"symbol": company["symbol"], "cik": company["cik"], "item": item,
                         "extraido": value, "xbrl": xbrl, "xbrl_filed": filed, "error_relativo": error,
                         "coincide": bool(error is not None and error <= TOLERANCE)})
        print(company["symbol"], sum(r["coincide"] for r in rows if r["symbol"] == company["symbol"]), flush=True)
    frame = pd.DataFrame(rows)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    suffix = f"-{subset}" if subset else ""
    frame.to_csv(OUTPUT / f"pilot{suffix}.csv", index=False)
    comparable = frame[frame.xbrl.notna()]
    summary = {"empresas": len(chosen), "tolerancia": TOLERANCE,
               "por_partida": {item: {"con_xbrl": int(len(g)), "extraidas": int(g.extraido.notna().sum()),
                                      "coinciden": int(g.coincide.sum()),
                                      "precision_sobre_extraidas": float(g.coincide.sum() / max(1, g.extraido.notna().sum())),
                                      "cobertura": float(g.extraido.notna().mean()) if len(g) else None}
                               for item, g in comparable.groupby("item")},
               "global": {"comparables": int(len(comparable)), "extraidas": int(comparable.extraido.notna().sum()),
                          "coinciden": int(comparable.coincide.sum()),
                          "error_mediano": float(np.nanmedian(comparable.error_relativo)) if comparable.error_relativo.notna().any() else None}}
    (OUTPUT / f"pilot{suffix}.json").write_text(json.dumps(fs._json_safe(summary), ensure_ascii=False, indent=2) + "\n",
                                       encoding="utf-8")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subset", choices=["ajuste", "reserva"])
    args = parser.parse_args()
    print(json.dumps(fs._json_safe(run(args.subset)), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
